import { mapsHref, phoneCallHref, socialProfiles, whatsappHref } from '../../config/siteSeo.js';

const IMG = '/images/afinix-landing';

export const heroSlides = [
    {
        kickerIcon: 'bi-calendar2-check',
        kicker: 'Entregas puntuales, sin reprogramaciones',
        kickerMobile: 'Entregas puntuales',
        titleBefore: 'Cumpla cada fecha. ',
        titleHighlight: 'Entregue cada caso con confianza.',
        titleAfter: '',
        copy: 'En AFINIX fabricamos sus casos con precisión digital, tiempos de entrega claros y seguimiento en cada etapa para que su clínica no se detenga.',
        copyMobile: 'Fabricamos sus casos con precisión digital, fechas claras y trazabilidad continua para que su clínica no se detenga.',
        ctaMain: 'Quiero trabajar con AFINIX',
        ctaSecondary: 'Ver servicios',
        image: `${IMG}/hero-equipment.jpg`,
        alt: 'Laboratorio dental digital en Arequipa con entregas puntuales y trazabilidad',
        floatCards: [
            { icon: 'bi-calendar2-check', label: 'CONFIANZA', value: 'Fechas de entrega confiables' },
            { icon: 'bi-search', label: 'TRAZABILIDAD', value: 'Seguimiento online' },
            { icon: 'bi-headset', label: 'RESPALDO', value: 'Soporte técnico para sus casos' },
        ],
    },
    {
        kickerIcon: 'bi-lightning-charge',
        kicker: 'Cero retoques en sillón',
        kickerMobile: 'Prótesis listas para cementar',
        titleBefore: 'Ajuste marginal exacto. ',
        titleHighlight: 'Su prótesis lista para cementar.',
        titleAfter: '',
        copy: 'Aprobación digital previa y producción CAD/CAM de máxima fidelidad. Cero desgastes en boca y más tiempo clínico para usted.',
        copyMobile: 'Producción CAD/CAM de máxima fidelidad con ajuste marginal exacto. Cero desgastes en boca y más tiempo clínico.',
        ctaMain: 'Enviar mi primer caso',
        ctaSecondary: 'Conocer nuestro flujo',
        image: `${IMG}/hero-production.jpg`,
        alt: 'Fresado CAD/CAM de alta precisión y ajuste oclusal exacto',
        floatCards: [
            { icon: 'bi-bullseye', label: 'AJUSTE', value: 'Sellado marginal micrónico' },
            { icon: 'bi-slash-circle', label: 'SILLÓN', value: '0 retoques oclusales' },
            { icon: 'bi-gem', label: 'BIOMATERIALES', value: 'Zirconia y e.max premium' },
        ],
    },
    {
        kickerIcon: 'bi-display',
        kicker: 'Control clínico antes de fresar',
        kickerMobile: 'Aprobación 3D en línea',
        titleBefore: 'Tome el control total. ',
        titleHighlight: 'Apruebe el diseño antes de producir.',
        titleAfter: '',
        copy: 'Revise el diseño 3D desde su celular o PC y envíe indicaciones directas al diseñador. Cero sorpresas en la prueba de estructura.',
        copyMobile: 'Revise el diseño 3D desde su celular y envíe indicaciones al diseñador. Cero sorpresas en la prueba clínica.',
        ctaMain: 'Solicitar acceso al portal',
        ctaSecondary: 'Consultar servicios',
        image: `${IMG}/hero-precision.jpg`,
        alt: 'Visualización y aprobación 3D de piezas dentales en línea',
        floatCards: [
            { icon: 'bi-box', label: 'CONTROL 3D', value: 'Visualizador interactivo' },
            { icon: 'bi-chat-left-dots', label: 'FEEDBACK', value: 'Comentarios en tiempo real' },
            { icon: 'bi-check2-square', label: 'PRODUCCIÓN', value: 'Fresado solo con visto bueno' },
        ],
    },
    {
        kickerIcon: 'bi-gift',
        kicker: 'Pruebe nuestro flujo digital',
        kickerMobile: '50% OFF primer caso',
        titleBefore: 'Pruebe AFINIX. ',
        titleHighlight: 'Envía tu primer caso con hasta 50% desc.',
        titleAfter: '',
        copy: 'Valide nuestro flujo digital en su clínica con respaldo total. Además, obtenga hasta 30% de descuento por cada colega referido.',
        copyMobile: 'Valide nuestro flujo digital en su clínica con respaldo total y tarifas preferenciales de bienvenida.',
        ctaMain: 'Enviar mi primer caso',
        ctaSecondary: 'Ver catálogo',
        image: `${IMG}/hero-precision.jpg`,
        alt: 'Prueba de laboratorio dental digital en Arequipa con descuento de bienvenida',
        floatCards: [
            { icon: 'bi-tag', label: 'BIENVENIDA', value: '50% OFF primer caso' },
            { icon: 'bi-people', label: 'RED COLEGAS', value: '30% OFF por referido' },
            { icon: 'bi-shield-check', label: 'GARANTÍA', value: 'Repetición 100% sin costo' },
        ],
    },
];

/** Pasos demo para el widget de seguimiento flotante (hero). */
export const heroTrackingSteps = [
    { id: '1', label: 'Caso registrado' },
    { id: '2', label: 'Diseño y aprobación' },
    { id: '3', label: 'Producción CAD/CAM' },
    { id: '4', label: 'Entrega trazable' },
];

export const services = [
    {
        name: 'Coronas en Zirconia',
        code: 'CAD-CROWN',
        detail: 'Alta resistencia biomecánica y estética funcional posterior. Fresado CAD/CAM para ajuste micrométrico y cero retoques en sillón.',
        leadTime: '48 horas',
        price: 'Cotización por caso',
        material: 'Zirconia multicapa',
        indication: 'Coronas unitarias posteriores y mixtas',
        image: `${IMG}/service-zirconia-crown.jpg`,
    },
    {
        name: 'Puentes en Zirconia',
        code: 'ZR-BRIDGE',
        detail: 'Estructuras múltiples diseñadas digitalmente para máxima rigidez estructural, asentamiento pasivo y estética uniforme.',
        leadTime: '72 horas',
        price: 'Según número de unidades',
        material: 'Zirconia multicapa',
        indication: 'Puentes anteriores y posteriores',
        image: `${IMG}/service-zirconia-bridge.jpg`,
    },
    {
        name: 'Coronas en Disilicato',
        code: 'EMAX-CROWN',
        detail: 'Máxima traslucidez y naturalidad anterior con disilicato de litio e.max de ajuste micrométrico.',
        leadTime: '48 horas',
        price: 'Cotización por caso',
        material: 'Disilicato e.max',
        indication: 'Coronas anteriores y premolares',
        image: `${IMG}/service-crown-disilicate.png`,
    },
    {
        name: 'Carillas en Disilicato',
        code: 'E.MAX-VENEER',
        detail: 'Disilicato de litio para máxima traslucidez y naturalidad anterior. Previsualización 3D y adhesión predecible.',
        leadTime: '48 horas',
        price: 'Desde evaluación estética',
        material: 'Disilicato e.max',
        indication: 'Carillas anteriores',
        image: `${IMG}/service-veneer-disilicate.jpg`,
    },
    {
        name: 'Carillas en Zirconia',
        code: 'ZR-VENEER',
        detail: 'Láminas ultrafinas de zirconia multicapa para alta resistencia y armonización estética.',
        leadTime: '48 horas',
        price: 'Cotización por caso',
        material: 'Zirconia multicapa',
        indication: 'Carillas y micro-preparaciones',
        image: `${IMG}/service-veneer-disilicate.jpg`,
    },
    {
        name: 'Provisionales en PMMA',
        code: 'PMMA-TEMP',
        detail: 'Fresado de alta densidad para proteger preparaciones clínicas, condicionar tejidos y validar oclusión y estética previa.',
        leadTime: '48 horas',
        price: 'Cotización por caso',
        material: 'PMMA multicapa',
        indication: 'Provisionales unitarios y múltiples',
        image: `${IMG}/service-provisional-pmma.jpg`,
    },
    {
        name: 'Guías Quirúrgicas 3D',
        code: 'SURG-GUIDE-3D',
        detail: 'Guías apilables con irrigación integrada. Planificación digital desde CBCT y escaneo intraoral para cirugías guiadas predecibles.',
        leadTime: '48 horas',
        price: 'A consultar',
        material: 'Resina biocompatible',
        indication: 'Cirugía guiada de implantes',
        image: `${IMG}/service-guide.jpg`,
    },
    {
        name: 'Coronas impresas en 3D',
        code: 'RESIN-CROWN-3D',
        detail: 'Resina de alta performance con carga cerámica. Ajuste marginal exacto y flujo digital ágil para restauraciones inmediatas.',
        leadTime: '48 horas',
        price: 'Cotización por caso',
        material: 'Resina cerámica',
        indication: 'Coronas unitarias anteriores y posteriores',
        image: `${IMG}/service-crown-resin-3d.jpg`,
    },
    {
        name: 'Carillas impresas en 3D',
        code: 'RESIN-VENEER-3D',
        detail: 'Carillas ultrafinas para optimizar forma, color y proporción en el sector anterior con mínima preparación y máxima precisión.',
        leadTime: '48 horas',
        price: 'Evaluación estética',
        material: 'Resina cerámica',
        indication: 'Carillas anteriores',
        image: `${IMG}/service-veneer-resin-3d.jpg`,
    },
    {
        name: 'Inlay-Onlay en 3D',
        code: 'INLAY-ONLAY-3D',
        detail: 'Restauraciones parciales que conservan tejido dental sano y devuelven anatomía oclusal precisa mediante tecnología digital.',
        leadTime: '48 horas',
        price: 'Cotización por caso',
        material: 'Resina composite / cerámica',
        indication: 'Restauraciones posteriores parciales',
        image: `${IMG}/service-inlay-onlay-3d.jpg`,
    },
    {
        name: 'Coronas sobre Implantes',
        code: 'IMPLANT-CROWN',
        detail: 'Solución atornillada o cementada con perfil de emergencia biológico y sellado pasivo exacto.',
        leadTime: '72 horas',
        price: 'Cotización por caso',
        material: 'Zirconia sobre Ti',
        indication: 'Rehabilitación sobre implantes',
        image: `${IMG}/service-implant-crown.png`,
    },
    {
        name: 'Prótesis Removibles PEEK',
        code: 'PEEK-PPR',
        detail: 'Estructuras ultraligeras y biocompatibles libres de metal, con módulo elástico similar al hueso.',
        leadTime: '96 horas',
        price: 'Cotización por caso',
        material: 'PEEK Biopolímero',
        indication: 'Rehabilitación removible estética',
        image: `${IMG}/service-ppr-peek.png`,
    },
    {
        name: 'Férulas Miorrelajantes',
        code: 'SPLINT-MICH',
        detail: 'Férulas oclusales tipo Michigan fresadas digitalmente para alivio articular y protección bruxómana.',
        leadTime: '72 horas',
        price: 'Cotización por caso',
        material: 'PMMA Cristalino',
        indication: 'Bruxismo y desórdenes ATM',
        image: `${IMG}/service-splint-michigan.png`,
    },
];

export const workflow = [
    {
        id: 'recepcion',
        number: '01',
        title: 'Recepción del caso',
        action: 'Validamos modelos o archivos',
        chips: ['Modelos o STL', 'Validación rápida'],
        text: 'Validamos modelos o archivos',
        icon: 'bi-cloud-arrow-up',
        status: 'Validamos modelos o archivos',
        tags: ['Control de calidad', 'Validación STL'],
        image: `${IMG}/workflow-reception.jpg`,
        imageAlt: 'Recepción de caso dental: envío del caso y revisión digital de la información',
        imagePosition: 'center',
        loginInsight: 'Auditoría inmediata de archivos antes de iniciar.',
    },
    {
        id: 'diseno',
        number: '02',
        title: 'Diseño 3D',
        action: 'Realizamos un diseño digital',
        chips: ['Diseño exocad', 'Ajuste oclusal'],
        text: 'Realizamos un diseño digital',
        icon: 'bi-bezier2',
        status: 'Realizamos un diseño digital',
        tags: ['Exocad Expert', 'Oclusión digital'],
        image: `${IMG}/workflow-design-3d.png`,
        imageAlt: 'Diseño 3D y planificación digital de alta precisión en exocad',
        imagePosition: 'center',
        loginInsight: 'Modelado 3D según anatomía y oclusión real.',
    },
    {
        id: 'aprobacion',
        number: '03',
        title: 'Revisión y aprobación',
        action: 'Apruebas el diseño propuesto',
        chips: ['Visor 3D online', 'Cero sorpresas'],
        text: 'Apruebas el diseño propuesto',
        icon: 'bi-person-check',
        status: 'Apruebas el diseño propuesto',
        tags: ['Cero sorpresas', 'Aprobación online'],
        image: `${IMG}/workflow-approval.png`,
        imageAlt: 'Profesional revisando información digital de un caso dental',
        imagePosition: 'center',
        loginInsight: 'Aprobación digital previa antes de fresar.',
    },
    {
        id: 'produccion',
        number: '04',
        title: 'Producción',
        action: 'Realizamos el fresado o impresión',
        chips: ['Fresado 5 ejes', 'Alta precisión'],
        text: 'Realizamos el fresado o impresión',
        icon: 'bi-cpu',
        status: 'Realizamos el fresado o impresión',
        tags: ['Alta tecnología', 'Fidelidad 3D'],
        image: `${IMG}/workflow-milling.png`,
        imageAlt: 'Equipo de fresado CAD CAM produciendo una restauración dental',
        imagePosition: 'center',
        loginInsight: 'Fresado CAD/CAM de 5 ejes con trazabilidad.',
    },
    {
        id: 'entrega',
        number: '05',
        title: 'Entrega y seguimiento',
        action: 'Enviamos tu caso a tiempo',
        chips: ['Despacho puntual', 'Historial digital'],
        text: 'Enviamos tu caso a tiempo',
        icon: 'bi-box-seam',
        status: 'Enviamos tu caso a tiempo',
        tags: ['Historial clínico', 'Garantía digital'],
        image: `${IMG}/workflow-delivery.png`,
        imageAlt: 'Prótesis dental terminada y preparada para su entrega',
        imagePosition: 'center',
        loginInsight: 'Entrega puntual y respaldo digital permanente.',
    },
];

export const partnerClinics = [
    ['CP', 'Clínica Prisma'],
    ['DN', 'Dental Norte'],
    ['IS', 'Implant Studio'],
    ['OP', 'Oral Prime'],
    ['SV', 'Sonrisa Viva'],
    ['CA', 'Centro Aligner'],
];

export const aboutMetrics = [
    {
        value: 'Arequipa Local',
        text: 'Soporte directo y cercano en tu ciudad. Sin demoras por envíos nacionales ni falta de comunicación.',
    },
    {
        value: '24/7 Disponible',
        text: 'Consulta el estado de tus casos, descarga diseños y sube archivos en cualquier momento desde el portal.',
    },
    {
        value: '5 Ejes',
        text: 'Tecnología alemana para casos de alta complejidad que exigen un ajuste marginal perfecto.',
    },
];

export const aboutGallery = [
    {
        src: `${IMG}/about-design-3d.png`,
        alt: 'Estación de diseño 3D y planificación digital en AFINIX Dental Lab',
    },
    {
        src: `${IMG}/about-materials-cadcam.png`,
        alt: 'Materiales CAD CAM cuidadosamente elegidos con alta resistencia y estética duradera',
    },
    {
        src: `${IMG}/workflow-milling.png`,
        alt: 'Equipo de fresado dental CAD/CAM en funcionamiento',
    },
];

export const mobileQuickLinks = [
    { href: '/#servicios', label: 'Servicios' },
    { href: '/#flujo', label: 'Flujo' },
];

/** Canales comerciales: WhatsApp + ubicación. */
export const contactChannels = [
    {
        label: 'WhatsApp',
        href: whatsappHref(),
        icon: 'bi-whatsapp',
        external: true,
    },
    {
        label: 'Ver ubicación',
        href: mapsHref(),
        icon: 'bi-geo-alt',
        external: true,
    },
];

export const landingContactChannels = [
    {
        id: 'whatsapp',
        title: 'WhatsApp',
        subtitle: 'Envíanos tus archivos o consulta tus dudas al instante.',
        btnText: 'Iniciar chat',
        href: whatsappHref(),
        icon: 'bi-whatsapp',
        colorClass: 'whatsapp',
        external: true,
    },
    {
        id: 'phone',
        title: 'Llamada Directa',
        subtitle: 'Atención rápida y directa para emergencias o coordinaciones.',
        btnText: 'Llamar ahora',
        href: phoneCallHref(),
        icon: 'bi-telephone',
        colorClass: 'phone',
        external: false,
    },
    {
        id: 'maps',
        title: 'Ubicación',
        subtitle: 'Visítanos en nuestro laboratorio dental en Arequipa.',
        btnText: 'Ver en Google Maps',
        href: mapsHref(),
        icon: 'bi-geo-alt',
        colorClass: 'maps',
        external: true,
    },
];

/** Redes sociales (URLs configurables vía VITE_* en siteSeo). */
export const socialLinks = [
    {
        label: 'Instagram',
        href: socialProfiles.instagram,
        icon: 'bi-instagram',
        external: true,
    },
    {
        label: 'Facebook',
        href: socialProfiles.facebook,
        icon: 'bi-facebook',
        external: true,
    },
    {
        label: 'TikTok',
        href: socialProfiles.tiktok,
        icon: 'bi-tiktok',
        external: true,
    },
];

export const landingMetrics = [
    { value: '3,000+', label: 'Casos entregados con éxito', icon: 'bi-check-all' },
    { value: '100%', label: 'Flujo digital y trazable', icon: 'bi-broadcast-pin' },
    { value: '98%', label: 'Satisfacción clínica en Arequipa', icon: 'bi-emoji-smile' },
    { value: '48h', label: 'Tiempo promedio de entrega', icon: 'bi-clock-history' },
];

