// Public service pages reuse references and artwork from the landing's marketing Services section.
// These codes identify static presentation items, not verified operational nl_productos SKUs.
export const SERVICE_PAGES = {
    '/zirconia-dental-arequipa': {
        eyebrow: 'Restauraciones CAD/CAM',
        intro: 'Coronas y puentes en zirconia para casos planificados junto al odontólogo. Cada indicación se revisa a partir de los archivos, la anatomía y los objetivos del caso antes de producir.',
        heroImage: '/images/afinix-landing/service-zirconia-real.jpg',
        heroAlt: 'Imagen de referencia de una restauración de zirconia',
        productCodes: ['CAD-CROWN', 'ZR-BRIDGE'],
        sectionTitle: 'Del registro clínico a la restauración',
        sectionText: 'Trabajamos el diseño digital de acuerdo con el tipo de restauración. La revisión previa permite conversar sobre forma, contactos y terminación antes del fresado y el acabado.',
        inputs: ['Escaneo o modelo del preparado y antagonista', 'Registro de mordida, color e indicaciones de diseño', 'Piezas a restaurar y referencias clínicas pertinentes'],
        note: 'La elección entre corona, puente o carilla de zirconia depende de la evaluación clínica. Los plazos y materiales se confirman para cada pedido.',
        related: ['/disilicato-emax-arequipa', '/coronas-cad-cam-arequipa'],
    },
    '/disilicato-emax-arequipa': {
        eyebrow: 'Restauraciones estéticas',
        intro: 'En nuestra sección Servicios presentamos coronas y carillas en disilicato de litio. La selección del producto y del color parte del plan clínico, no de una solución única para todos los pacientes.',
        heroImage: '/images/afinix-landing/service-crown-disilicate.png',
        heroAlt: 'Imagen de referencia de una corona de disilicato',
        heroContain: true,
        productCodes: ['EMAX-CROWN', 'E.MAX-VENEER'],
        sectionTitle: 'Diseño con referencias claras',
        sectionText: 'Compartir fotografías, referencia de color y archivos completos ayuda a definir el diseño de coronas y carillas. Cuando el flujo del caso lo permite, el diseño se revisa antes de fabricar.',
        inputs: ['Escaneo o modelo de trabajo y antagonista', 'Color VITA y fotografías de referencia cuando correspondan', 'Piezas, tipo de restauración e indicaciones del odontólogo'],
        note: 'El odontólogo define la indicación y el protocolo de cementación. AFINIX confirma la viabilidad técnica tras revisar cada caso.',
        related: ['/zirconia-dental-arequipa', '/coronas-cad-cam-arequipa'],
    },
    '/guias-quirurgicas-dentales-arequipa': {
        eyebrow: 'Planificación implantológica',
        intro: 'En nuestra sección Servicios presentamos guías quirúrgicas impresas en 3D. Las características, como diseño apilable o irrigación, se evalúan según el plan del profesional tratante y la viabilidad técnica.',
        heroImage: '/images/afinix-landing/service-guide.jpg',
        heroAlt: 'Imagen de referencia de una guía quirúrgica impresa en 3D',
        heroContain: true,
        productCodes: ['SURG-GUIDE-3D'],
        sectionTitle: 'Un plan compartido antes de imprimir',
        sectionText: 'El laboratorio necesita alinear el escaneo de superficie, las imágenes y el plan de implantes. Antes de producir se revisa que los registros correspondan al mismo caso y sean suficientes para el diseño solicitado.',
        inputs: ['CBCT y escaneo o modelo digital según el protocolo', 'Plan de implantes e indicaciones quirúrgicas del profesional', 'Referencias de apoyo, dientes y estructura disponible'],
        note: 'La guía es un auxiliar fabricado conforme al plan clínico; no sustituye la planificación ni el criterio quirúrgico del odontólogo.',
        related: ['/protesis-sobre-implantes-arequipa', '/flujo-digital'],
    },
    '/protesis-sobre-implantes-arequipa': {
        eyebrow: 'Rehabilitación implantosoportada',
        intro: 'En nuestra sección Servicios presentamos coronas sobre implantes. Evaluamos el diseño y la fabricación a partir del sistema implantológico, los componentes y los registros de cada caso.',
        heroImage: '/images/afinix-landing/service-implant-crown.png',
        heroAlt: 'Imagen de referencia de coronas sobre implantes',
        heroContain: true,
        productCodes: ['IMPLANT-CROWN'],
        sectionTitle: 'Compatibilidad y registros del caso',
        sectionText: 'Antes de diseñar verificamos la información del implante, la conexión protésica y los componentes enviados o indicados. Si falta un dato esencial, lo consultamos antes de fabricar.',
        inputs: ['Sistema, plataforma y componentes protésicos previstos', 'Escaneo o modelo con registros de implante y antagonista', 'Color, pieza e indicaciones del odontólogo'],
        note: 'Las rehabilitaciones múltiples o híbridas requieren evaluación individual. La corona sobre implante es una referencia de la sección Servicios; confirma el producto concreto al consultar.',
        related: ['/guias-quirurgicas-dentales-arequipa', '/zirconia-dental-arequipa'],
    },
    '/impresion-3d-dental-arequipa': {
        eyebrow: 'Fabricación digital',
        intro: 'En nuestra sección Servicios mostramos ejemplos de guías y restauraciones impresas en 3D. El diseño, el material y la disponibilidad se confirman para la indicación concreta de cada caso.',
        heroImage: '/images/afinix-landing/service-crown-resin-3d.jpg',
        heroAlt: 'Imagen de referencia de una corona impresa en 3D',
        heroContain: true,
        productCodes: ['SURG-GUIDE-3D', 'RESIN-CROWN-3D', 'RESIN-VENEER-3D', 'INLAY-ONLAY-3D'],
        sectionTitle: 'Qué podemos revisar contigo',
        sectionText: 'El tipo de archivo, la indicación clínica y la finalidad de la pieza determinan el flujo de diseño y fabricación. No toda resina sirve para la misma aplicación; confirmamos el producto antes de iniciar.',
        inputs: ['Archivo digital del caso y registros de mordida cuando correspondan', 'Producto solicitado, piezas y finalidad clínica', 'Color y referencias adicionales para restauraciones'],
        note: 'Disponibilidad, material y plazo se confirman al evaluar el archivo y la indicación concreta.',
        related: ['/guias-quirurgicas-dentales-arequipa', '/flujo-digital'],
    },
    '/flujo-digital': {
        eyebrow: 'Clínica + laboratorio',
        intro: 'Un caso pasa por recepción de archivos, diseño, revisión, producción y entrega. El portal reúne seguimiento y comunicación para que tu equipo conozca en qué etapa se encuentra su pedido.',
        heroImage: '/images/afinix-landing/workflow-design-3d.jpg',
        heroAlt: 'Diseño digital de una restauración en el flujo de AFINIX Dental Lab',
        heroContain: true,
        workflow: true,
        sectionTitle: 'Cada etapa necesita una decisión clara',
        sectionText: 'Un archivo completo permite iniciar el trabajo; la revisión del diseño, cuando aplica, permite resolver observaciones antes de producir. El flujo cambia según el producto y la complejidad del pedido.',
        inputs: ['Registros y archivos del caso', 'Producto, piezas, material y color solicitados', 'Fecha clínica y modalidad de entrega a coordinar'],
        note: 'La revisión 3D y los pasos de aprobación se coordinan según el tipo de trabajo; no todos los pedidos requieren la misma secuencia.',
        related: ['/para-clinicas', '/coronas-cad-cam-arequipa'],
    },
    '/para-clinicas': {
        eyebrow: 'Una forma más clara de colaborar',
        intro: 'AFINIX Dental Lab trabaja con clínicas y consultorios que necesitan coordinar casos dentales con documentación, seguimiento y comunicación entre el profesional y el laboratorio.',
        heroImage: '/images/afinix-landing/hero-lab.jpg',
        heroAlt: 'Entorno de laboratorio dental digital',
        productCodes: ['CAD-CROWN', 'EMAX-CROWN', 'IMPLANT-CROWN', 'SURG-GUIDE-3D'],
        sectionTitle: 'Tu equipo conserva el contexto del pedido',
        sectionText: 'El portal organiza el estado y los datos de cada trabajo. Cuando un paciente necesita productos diferentes, cada trabajo técnico se registra como una orden independiente para conservar su propio flujo.',
        inputs: ['Datos de la clínica y contacto responsable', 'Datos clínicos y archivos del trabajo específico', 'Indicaciones, fecha clínica y entrega solicitada'],
        note: 'Si aún no tienes acceso al portal, escríbenos para coordinar el primer caso y el registro de tu clínica.',
        related: ['/flujo-digital', '/coronas-cad-cam-arequipa'],
    },
};
